/* =========================================================================
   DATI DELL'APP  —  PREZZI TARATI SU LIDL (scontrini reali, feb–giu 2026)

   - SUPERMERCATI: Lidl = riferimento (moltiplicatore 1.00). Gli altri sono
     stimati rispetto a Lidl.
   - OFFERTE: sconti del volantino (chiave = nome ingrediente minuscolo,
     valore = moltiplicatore, es. 0.7 = -30%). Vuoto finché non arriva il volantino.
   - ELETTRODOMESTICI: "Cosa hai in cucina?".
   - CATEGORIE: reparti in ordine, per la lista della spesa.
   - RICETTE: la libreria da cui l'app pesca.

   NOTA prezzi: sono il costo della QUANTITÀ usata nella ricetta (per 2 porzioni),
   ai prezzi Lidl. Al supermercato compri confezioni intere (es. il pollo a €6,99
   dura più pasti): la stima settimanale è quindi un po' più bassa dello scontrino
   reale, che include anche extra non-cibo. Calibrabili in ogni momento.
   ========================================================================= */

const SUPERMERCATI = [
  { id: "lidl",      nome: "Lidl",      moltiplicatore: 1.00, colore: "#0a4f9e", testo: "#ffd400" },
  { id: "eurospin",  nome: "Eurospin",  moltiplicatore: 0.97, colore: "#10294d", testo: "#ffffff" },
  { id: "penny",     nome: "Penny",     moltiplicatore: 0.98, colore: "#d81e05", testo: "#ffffff" },
  { id: "aldi",      nome: "Aldi",      moltiplicatore: 0.97, colore: "#0b5cab", testo: "#ffffff" },
  { id: "coop",      nome: "Coop",      moltiplicatore: 1.15, colore: "#c1122f", testo: "#ffffff" },
  { id: "esselunga", nome: "Esselunga", moltiplicatore: 1.18, colore: "#e26a5f", testo: "#ffffff" },
  { id: "conad",     nome: "Conad",     moltiplicatore: 1.12, colore: "#ec6608", testo: "#ffffff" },
  { id: "carrefour", nome: "Carrefour", moltiplicatore: 1.12, colore: "#035f9f", testo: "#ffffff" },
  { id: "bennet",    nome: "Bennet",    moltiplicatore: 1.12, colore: "#019a4d", testo: "#ffffff" },
];

const OFFERTE = {};

const ELETTRODOMESTICI = {
  fornelli:    { nome: "Fornelli",          emoji: "🔥" },
  forno:       { nome: "Forno",             emoji: "🔲" },
  microonde:   { nome: "Microonde",         emoji: "📟" },
  friggitrice: { nome: "Friggitrice ad aria", emoji: "🍟" },
};

const CATEGORIE = [
  "Frutta e verdura",
  "Carne e pesce",
  "Latticini e uova",
  "Pane e panetteria",
  "Pasta, riso e cereali",
  "Scatolame e conserve",
  "Condimenti e spezie",
  "Surgelati",
  "Bevande",
  "Dolci e snack",
];

const TIPI_PASTO = {
  veloce:    "Veloce e facile",
  proteico:  "Iperproteico",
  sano:      "Sano e leggero",
  classico:  "Classico italiano",
  economico: "Economico",
  sfizioso:  "Sfizioso",
};

const DIETE = {
  vegetariano:    "Vegetariano",
  vegano:         "Vegano",
  pescetariano:   "Pescetariano",
  senza_glutine:  "Senza glutine",
  senza_lattosio: "Senza lattosio",
  iperproteico:   "Iperproteico",
};

const ALLERGENI = {
  glutine:          "Glutine",
  lattosio:         "Lattosio",
  uova:             "Uova",
  frutta_a_guscio:  "Frutta a guscio",
  pesce:            "Pesce",
  crostacei:        "Crostacei",
  soia:             "Soia",
};

const SLOT = { colazione: "Colazione", pranzo: "Pranzo", cena: "Cena" };

const STAGIONI = { primavera: "Primavera", estate: "Estate", autunno: "Autunno", inverno: "Inverno" };

/* -------------------------------------------------------------------------
   LIBRERIA RICETTE  (ogni ricetta vale per 2 porzioni)
   Campi: id, nome, emoji, tempo(min), slot, attrezzatura([]=niente),
   riscaldabile(false = da mangiare al momento, non da ufficio; assente=true),
   piccante(assente=no), stagioni(assente=tutto l'anno), tipi, diete, allergeni,
   nutrizione(per porzione), ingredienti{nome,categoria,quantita,prezzo €/2porzioni}, passi.
   ------------------------------------------------------------------------- */
const RICETTE = [

  /* ---------- COLAZIONI ---------- */
  {
    id: "yogurt_proteico_frutta",
    nome: "Yogurt proteico con frutta e mandorle",
    emoji: "🥣", tempo: 5, slot: ["colazione"], attrezzatura: [],
    tipi: ["proteico", "veloce", "sano"],
    diete: ["vegetariano", "senza_glutine", "iperproteico"],
    allergeni: ["lattosio", "frutta_a_guscio"],
    nutrizione: { kcal: 340, proteine: 28, carboidrati: 30, grassi: 12 },
    ingredienti: [
      { nome: "Yogurt proteico (Skyr)", categoria: "Latticini e uova",   quantita: "300 g",  prezzo: 1.60 },
      { nome: "Frutta fresca",       categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.90 },
      { nome: "Mandorle",            categoria: "Dolci e snack",          quantita: "30 g",   prezzo: 0.60 },
      { nome: "Miele",               categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.20 },
    ],
    passi: [
      "Versa lo yogurt proteico in due ciotole.",
      "Aggiungi la frutta a pezzi e le mandorle tritate.",
      "Completa con un filo di miele e servi.",
    ],
  },
  {
    id: "porridge_proteico",
    nome: "Porridge proteico al burro d'arachidi",
    emoji: "🥣", tempo: 10, slot: ["colazione"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio", "frutta_a_guscio"],
    nutrizione: { kcal: 410, proteine: 22, carboidrati: 46, grassi: 15 },
    ingredienti: [
      { nome: "Fiocchi d'avena",     categoria: "Pasta, riso e cereali",  quantita: "100 g",  prezzo: 0.40 },
      { nome: "Latte",               categoria: "Latticini e uova",       quantita: "300 ml", prezzo: 0.30 },
      { nome: "Crema di arachidi",   categoria: "Dolci e snack",          quantita: "30 g",   prezzo: 0.35 },
      { nome: "Banana",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
    ],
    passi: [
      "Scalda il latte con l'avena mescolando finché si addensa.",
      "Aggiungi la crema di arachidi e mescola.",
      "Completa con la banana a rondelle e servi.",
    ],
  },
  {
    id: "pancake_proteici",
    nome: "Pancake proteici alla banana",
    emoji: "🥞", tempo: 15, slot: ["colazione"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sfizioso"],
    diete: ["vegetariano", "iperproteico"],
    allergeni: ["glutine", "uova", "lattosio"],
    nutrizione: { kcal: 380, proteine: 24, carboidrati: 45, grassi: 9 },
    ingredienti: [
      { nome: "Banana",              categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.40 },
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "2",      prezzo: 0.56 },
      { nome: "Fiocchi d'avena",     categoria: "Pasta, riso e cereali",  quantita: "100 g",  prezzo: 0.40 },
      { nome: "Latte",               categoria: "Latticini e uova",       quantita: "100 ml", prezzo: 0.10 },
    ],
    passi: [
      "Frulla banana, uova, avena e latte fino a ottenere una pastella.",
      "Cuoci piccoli pancake in padella antiaderente, 2 minuti per lato.",
      "Impila e servi, volendo con altra frutta.",
    ],
  },
  {
    id: "yogurt_muesli",
    nome: "Yogurt greco con muesli e frutti di bosco",
    emoji: "🫐", tempo: 5, slot: ["colazione"], attrezzatura: [],
    tipi: ["veloce", "proteico", "sano"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["lattosio", "frutta_a_guscio"],
    nutrizione: { kcal: 320, proteine: 18, carboidrati: 38, grassi: 10 },
    ingredienti: [
      { nome: "Yogurt greco",        categoria: "Latticini e uova",       quantita: "300 g",  prezzo: 1.60 },
      { nome: "Muesli",              categoria: "Pasta, riso e cereali",  quantita: "80 g",   prezzo: 0.60 },
      { nome: "Frutti di bosco",     categoria: "Frutta e verdura",       quantita: "120 g",  prezzo: 1.80 },
      { nome: "Miele",               categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.20 },
    ],
    passi: [
      "Versa lo yogurt greco in due ciotole.",
      "Aggiungi il muesli e i frutti di bosco.",
      "Completa con un filo di miele e servi.",
    ],
  },
  {
    id: "porridge_mela",
    nome: "Porridge di avena con mela e cannella",
    emoji: "🥣", tempo: 10, slot: ["colazione"], attrezzatura: ["fornelli"],
    tipi: ["sano", "economico"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 300, proteine: 9, carboidrati: 52, grassi: 6 },
    ingredienti: [
      { nome: "Fiocchi d'avena",     categoria: "Pasta, riso e cereali",  quantita: "120 g",  prezzo: 0.45 },
      { nome: "Latte",               categoria: "Latticini e uova",       quantita: "400 ml", prezzo: 0.40 },
      { nome: "Mela",                categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.25 },
      { nome: "Cannella",            categoria: "Condimenti e spezie",    quantita: "1 pizzico", prezzo: 0.05 },
    ],
    passi: [
      "Scalda il latte con l'avena mescolando finché si addensa.",
      "Aggiungi la mela a cubetti e la cannella.",
      "Lascia riposare un minuto e servi caldo.",
    ],
  },
  {
    id: "toast_avocado_uovo",
    nome: "Toast integrale con avocado e uovo",
    emoji: "🥑", tempo: 10, slot: ["colazione", "pranzo"], attrezzatura: ["fornelli"],
    riscaldabile: false,
    tipi: ["sano", "proteico"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "uova"],
    nutrizione: { kcal: 360, proteine: 16, carboidrati: 30, grassi: 18 },
    ingredienti: [
      { nome: "Pane integrale",      categoria: "Pane e panetteria",      quantita: "4 fette", prezzo: 0.50 },
      { nome: "Avocado",             categoria: "Frutta e verdura",       quantita: "1",      prezzo: 1.00 },
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "2",      prezzo: 0.56 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
    ],
    passi: [
      "Tosta il pane. Schiaccia l'avocado con sale e succo di limone.",
      "Cuoci le uova in camicia o all'occhio di bue.",
      "Spalma l'avocado sul pane, adagia l'uovo e servi.",
    ],
  },
  {
    id: "budino_chia",
    nome: "Budino di chia al cocco (vegano)",
    emoji: "🍮", tempo: 5, slot: ["colazione"], attrezzatura: [],
    tipi: ["sano", "veloce"],
    diete: ["vegetariano", "vegano", "senza_lattosio", "senza_glutine"],
    allergeni: [],
    nutrizione: { kcal: 290, proteine: 7, carboidrati: 28, grassi: 16 },
    ingredienti: [
      { nome: "Semi di chia",        categoria: "Pasta, riso e cereali",  quantita: "60 g",   prezzo: 0.90 },
      { nome: "Bevanda al cocco",    categoria: "Bevande",                quantita: "400 ml", prezzo: 0.80 },
      { nome: "Sciroppo d'acero",    categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.40 },
      { nome: "Frutta fresca",       categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.90 },
    ],
    passi: [
      "Mescola semi di chia e bevanda al cocco con lo sciroppo.",
      "Lascia in frigo almeno 3 ore (meglio tutta la notte).",
      "Completa con la frutta fresca prima di servire.",
    ],
  },
  {
    id: "fette_marmellata",
    nome: "Fette biscottate con marmellata",
    emoji: "🍞", tempo: 5, slot: ["colazione"], attrezzatura: [],
    tipi: ["veloce", "economico", "classico"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 260, proteine: 6, carboidrati: 50, grassi: 4 },
    ingredienti: [
      { nome: "Fette biscottate",    categoria: "Pane e panetteria",      quantita: "6",      prezzo: 0.40 },
      { nome: "Marmellata",          categoria: "Dolci e snack",          quantita: "4 cucchiai", prezzo: 0.45 },
      { nome: "Caffè",               categoria: "Bevande",                quantita: "2 tazze", prezzo: 0.20 },
    ],
    passi: [
      "Prepara il caffè.",
      "Spalma la marmellata sulle fette biscottate.",
      "Servi subito.",
    ],
  },

  /* ---------- PRANZI / CENE ---------- */
  {
    id: "pollo_ceci_feta",
    nome: "Insalata di pollo, ceci e feta",
    emoji: "🥗", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano"],
    diete: ["senza_glutine", "iperproteico"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 430, proteine: 40, carboidrati: 28, grassi: 18 },
    ingredienti: [
      { nome: "Petto di pollo",      categoria: "Carne e pesce",          quantita: "250 g",  prezzo: 1.75 },
      { nome: "Ceci lessati",        categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.50 },
      { nome: "Feta",                categoria: "Latticini e uova",       quantita: "80 g",   prezzo: 0.80 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Cuoci il pollo in padella e taglialo a strisce.",
      "Unisci ceci scolati, pomodorini e feta a cubetti.",
      "Aggiungi il pollo, condisci con olio e servi (ottima anche fredda).",
    ],
  },
  {
    id: "riso_tonno_freddo",
    nome: "Riso freddo con tonno, mais e pomodorini",
    emoji: "🍚", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "veloce", "sano"],
    diete: ["pescetariano", "senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: ["pesce"],
    nutrizione: { kcal: 460, proteine: 30, carboidrati: 60, grassi: 10 },
    ingredienti: [
      { nome: "Riso",                categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 0.40 },
      { nome: "Tonno in scatola",    categoria: "Scatolame e conserve",   quantita: "160 g",  prezzo: 1.40 },
      { nome: "Mais",                categoria: "Scatolame e conserve",   quantita: "150 g",  prezzo: 0.60 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.15 },
    ],
    passi: [
      "Lessa il riso, scolalo e raffreddalo sotto acqua fredda.",
      "Unisci tonno, mais e pomodorini.",
      "Condisci con olio e servi freddo (perfetto da portare al lavoro).",
    ],
  },
  {
    id: "tacchino_farro_zucchine",
    nome: "Tacchino con farro e zucchine",
    emoji: "🥘", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano"],
    diete: ["iperproteico"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 470, proteine: 40, carboidrati: 50, grassi: 12 },
    ingredienti: [
      { nome: "Fesa di tacchino",    categoria: "Carne e pesce",          quantita: "250 g",  prezzo: 2.20 },
      { nome: "Farro",               categoria: "Pasta, riso e cereali",  quantita: "160 g",  prezzo: 0.65 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.85 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa il farro. Salta le zucchine a rondelle in padella.",
      "Aggiungi il tacchino a dadini e cuoci finché dorato.",
      "Unisci il farro, manteca e servi (si riscalda benissimo).",
    ],
  },
  {
    id: "uova_patate_fagiolini",
    nome: "Insalata proteica di uova, patate e fagiolini",
    emoji: "🥚", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano", "economico"],
    diete: ["vegetariano", "senza_glutine", "senza_lattosio"],
    allergeni: ["uova"],
    nutrizione: { kcal: 380, proteine: 22, carboidrati: 34, grassi: 16 },
    ingredienti: [
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "4",      prezzo: 1.12 },
      { nome: "Patate",              categoria: "Frutta e verdura",       quantita: "300 g",  prezzo: 0.45 },
      { nome: "Fagiolini",           categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 1.10 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa patate e fagiolini; rassoda le uova.",
      "Taglia tutto a pezzi e unisci.",
      "Condisci con olio, sale e pepe; ottima anche fredda.",
    ],
  },
  {
    id: "frittata_forno_spinaci",
    nome: "Frittata al forno con spinaci e ricotta",
    emoji: "🍳", tempo: 30, slot: ["pranzo", "cena"], attrezzatura: ["forno"],
    tipi: ["proteico", "sano"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["uova", "lattosio"],
    nutrizione: { kcal: 360, proteine: 26, carboidrati: 8, grassi: 24 },
    ingredienti: [
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "5",      prezzo: 1.40 },
      { nome: "Spinaci",             categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 1.30 },
      { nome: "Ricotta",             categoria: "Latticini e uova",       quantita: "100 g",  prezzo: 0.65 },
      { nome: "Parmigiano",          categoria: "Latticini e uova",       quantita: "30 g",   prezzo: 0.55 },
    ],
    passi: [
      "Sbatti le uova con ricotta e parmigiano; unisci gli spinaci.",
      "Versa in una teglia e cuoci in forno a 180° per 20 minuti.",
      "Taglia a quadrotti; si riscalda perfettamente al microonde.",
    ],
  },
  {
    id: "merluzzo_patate",
    nome: "Bastoncini di merluzzo al forno con patate",
    emoji: "🐟", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["forno"],
    tipi: ["proteico", "veloce", "economico"],
    diete: ["pescetariano", "senza_lattosio"],
    allergeni: ["pesce", "glutine"],
    nutrizione: { kcal: 450, proteine: 28, carboidrati: 42, grassi: 18 },
    ingredienti: [
      { nome: "Bastoncini di merluzzo", categoria: "Surgelati",           quantita: "1 confezione", prezzo: 2.99 },
      { nome: "Patate",              categoria: "Frutta e verdura",       quantita: "300 g",  prezzo: 0.45 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.25 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.15 },
    ],
    passi: [
      "Taglia le patate a spicchi, condiscile e inforna a 200° per 20 minuti.",
      "Aggiungi i bastoncini e cuoci altri 12-15 minuti, girandoli a metà.",
      "Servi con una spruzzata di limone.",
    ],
  },
  {
    id: "couscous_pollo_verdure",
    nome: "Couscous con pollo e verdure",
    emoji: "🍲", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano", "veloce"],
    diete: ["iperproteico"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 520, proteine: 38, carboidrati: 58, grassi: 12 },
    ingredienti: [
      { nome: "Couscous",            categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 1.10 },
      { nome: "Petto di pollo",      categoria: "Carne e pesce",          quantita: "250 g",  prezzo: 1.75 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.45 },
      { nome: "Peperoni",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.65 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Salta pollo a dadini e verdure a cubetti in padella con un filo d'olio.",
      "Prepara il couscous idratandolo con acqua calda salata.",
      "Sgrana il couscous e uniscilo a pollo e verdure; ottimo anche freddo.",
    ],
  },
  {
    id: "piadina_prosciutto",
    nome: "Piadina con prosciutto cotto e insalata",
    emoji: "🌯", tempo: 8, slot: ["pranzo", "cena"], attrezzatura: [],
    tipi: ["veloce", "sfizioso"],
    diete: [],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 480, proteine: 24, carboidrati: 45, grassi: 22 },
    ingredienti: [
      { nome: "Piadina",            categoria: "Pane e panetteria",      quantita: "2",      prezzo: 1.19 },
      { nome: "Prosciutto cotto",   categoria: "Carne e pesce",          quantita: "100 g",  prezzo: 1.69 },
      { nome: "Insalata iceberg",   categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.45 },
      { nome: "Mozzarella",         categoria: "Latticini e uova",       quantita: "125 g",  prezzo: 1.49 },
    ],
    passi: [
      "Scalda leggermente le piadine.",
      "Farcisci con prosciutto, mozzarella e insalata.",
      "Arrotola e servi (si porta benissimo, anche fredda).",
    ],
  },
  {
    id: "pasta_pomodoro",
    nome: "Pasta al pomodoro e basilico",
    emoji: "🍝", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["veloce", "economico", "classico"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 450, proteine: 13, carboidrati: 82, grassi: 8 },
    ingredienti: [
      { nome: "Pasta",               categoria: "Pasta, riso e cereali",  quantita: "200 g",  prezzo: 0.40 },
      { nome: "Passata di pomodoro", categoria: "Scatolame e conserve",   quantita: "300 g",  prezzo: 0.55 },
      { nome: "Basilico",            categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.40 },
      { nome: "Aglio",               categoria: "Frutta e verdura",       quantita: "1 spicchio", prezzo: 0.10 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Soffriggi l'aglio nell'olio, aggiungi la passata e cuoci 10 minuti.",
      "Lessa la pasta al dente e scolala.",
      "Manteca con il sugo, aggiungi il basilico e servi.",
    ],
  },
  {
    id: "risotto_funghi",
    nome: "Risotto ai funghi",
    emoji: "🍚", tempo: 30, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["autunno", "inverno"],
    tipi: ["classico", "sfizioso"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 480, proteine: 12, carboidrati: 78, grassi: 12 },
    ingredienti: [
      { nome: "Riso Carnaroli",      categoria: "Pasta, riso e cereali",  quantita: "200 g",  prezzo: 0.80 },
      { nome: "Funghi champignon",   categoria: "Frutta e verdura",       quantita: "250 g",  prezzo: 1.50 },
      { nome: "Cipolla",             categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
      { nome: "Parmigiano",          categoria: "Latticini e uova",       quantita: "40 g",   prezzo: 0.72 },
      { nome: "Brodo vegetale",      categoria: "Scatolame e conserve",   quantita: "750 ml", prezzo: 0.30 },
    ],
    passi: [
      "Soffriggi la cipolla, aggiungi i funghi e falli rosolare.",
      "Tosta il riso, sfuma e cuoci aggiungendo brodo poco alla volta.",
      "Manteca con il parmigiano e servi.",
    ],
  },
  {
    id: "farro_verdure_feta",
    nome: "Insalata di farro con verdure e feta",
    emoji: "🥗", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["primavera", "estate"],
    tipi: ["sano", "veloce"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 420, proteine: 15, carboidrati: 58, grassi: 14 },
    ingredienti: [
      { nome: "Farro",               categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 0.70 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 0.90 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.45 },
      { nome: "Feta",                categoria: "Latticini e uova",       quantita: "100 g",  prezzo: 1.00 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa il farro e raffreddalo sotto acqua fredda.",
      "Taglia pomodorini e zucchine a cubetti (le zucchine saltate in padella).",
      "Unisci tutto con la feta sbriciolata, condisci con olio e servi.",
    ],
  },
  {
    id: "pollo_griglia_verdure",
    nome: "Pollo alla griglia con verdure al forno",
    emoji: "🍗", tempo: 35, slot: ["pranzo", "cena"], attrezzatura: ["fornelli", "forno"],
    tipi: ["proteico", "sano"],
    diete: ["senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: [],
    nutrizione: { kcal: 430, proteine: 42, carboidrati: 22, grassi: 18 },
    ingredienti: [
      { nome: "Petto di pollo",      categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 2.10 },
      { nome: "Peperoni",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.65 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.45 },
      { nome: "Patate",              categoria: "Frutta e verdura",       quantita: "300 g",  prezzo: 0.45 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Taglia le verdure, condiscile e cuoci in forno a 200° per 25 minuti.",
      "Griglia il petto di pollo 4-5 minuti per lato.",
      "Servi il pollo con le verdure al forno.",
    ],
  },
  {
    id: "salmone_patate",
    nome: "Salmone al forno con patate",
    emoji: "🐟", tempo: 30, slot: ["pranzo", "cena"], attrezzatura: ["forno"],
    tipi: ["proteico", "sfizioso"],
    diete: ["pescetariano", "senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: ["pesce"],
    nutrizione: { kcal: 520, proteine: 38, carboidrati: 30, grassi: 26 },
    ingredienti: [
      { nome: "Filetto di salmone",  categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 5.40 },
      { nome: "Patate",              categoria: "Frutta e verdura",       quantita: "400 g",  prezzo: 0.60 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.25 },
      { nome: "Rosmarino",           categoria: "Condimenti e spezie",    quantita: "1 rametto", prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Taglia le patate a spicchi e infornale a 200° per 15 minuti.",
      "Aggiungi il salmone con limone e rosmarino, cuoci altri 15 minuti.",
      "Servi caldo.",
    ],
  },
  {
    id: "frittata_zucchine",
    nome: "Frittata di zucchine",
    emoji: "🍳", tempo: 15, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["veloce", "economico", "proteico"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["uova", "lattosio"],
    nutrizione: { kcal: 340, proteine: 24, carboidrati: 8, grassi: 24 },
    ingredienti: [
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "5",      prezzo: 1.40 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.85 },
      { nome: "Parmigiano",          categoria: "Latticini e uova",       quantita: "30 g",   prezzo: 0.55 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.15 },
    ],
    passi: [
      "Affetta le zucchine e falle appassire in padella.",
      "Sbatti le uova con il parmigiano, sale e pepe.",
      "Versa sulle zucchine e cuoci la frittata su entrambi i lati.",
    ],
  },
  {
    id: "zuppa_lenticchie",
    nome: "Zuppa di lenticchie",
    emoji: "🍲", tempo: 45, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["autunno", "inverno"],
    tipi: ["sano", "economico"],
    diete: ["vegetariano", "vegano", "senza_glutine", "senza_lattosio"],
    allergeni: [],
    nutrizione: { kcal: 360, proteine: 20, carboidrati: 52, grassi: 6 },
    ingredienti: [
      { nome: "Lenticchie secche",   categoria: "Scatolame e conserve",   quantita: "200 g",  prezzo: 0.55 },
      { nome: "Carota",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.15 },
      { nome: "Sedano",              categoria: "Frutta e verdura",       quantita: "1 costa", prezzo: 0.15 },
      { nome: "Cipolla",             categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Passata di pomodoro", categoria: "Scatolame e conserve",   quantita: "150 g",  prezzo: 0.30 },
    ],
    passi: [
      "Prepara un soffritto con carota, sedano e cipolla.",
      "Aggiungi lenticchie, passata e acqua/brodo a coprire.",
      "Cuoci 35-40 minuti finché le lenticchie sono morbide.",
    ],
  },
  {
    id: "pasta_pesto",
    nome: "Pasta integrale al pesto",
    emoji: "🌿", tempo: 15, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["veloce", "classico"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio", "frutta_a_guscio"],
    nutrizione: { kcal: 540, proteine: 16, carboidrati: 76, grassi: 20 },
    ingredienti: [
      { nome: "Pasta integrale",     categoria: "Pasta, riso e cereali",  quantita: "200 g",  prezzo: 0.45 },
      { nome: "Pesto",               categoria: "Scatolame e conserve",   quantita: "120 g",  prezzo: 1.30 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
    ],
    passi: [
      "Lessa la pasta al dente.",
      "Scolala tenendo un po' d'acqua di cottura e condisci con il pesto.",
      "Aggiungi i pomodorini tagliati a metà e servi.",
    ],
  },
  {
    id: "polpette_sugo",
    nome: "Polpette di manzo al sugo",
    emoji: "🍖", tempo: 40, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["classico", "proteico", "sfizioso"],
    diete: ["iperproteico"],
    allergeni: ["glutine", "uova", "lattosio"],
    nutrizione: { kcal: 480, proteine: 34, carboidrati: 24, grassi: 28 },
    ingredienti: [
      { nome: "Macinato di manzo",   categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 2.50 },
      { nome: "Pangrattato",         categoria: "Pane e panetteria",      quantita: "50 g",   prezzo: 0.20 },
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "1",      prezzo: 0.28 },
      { nome: "Passata di pomodoro", categoria: "Scatolame e conserve",   quantita: "400 g",  prezzo: 0.75 },
      { nome: "Parmigiano",          categoria: "Latticini e uova",       quantita: "30 g",   prezzo: 0.55 },
    ],
    passi: [
      "Impasta manzo, pangrattato, uovo e parmigiano; forma le polpette.",
      "Rosolale in padella, poi aggiungi la passata.",
      "Cuoci 20 minuti nel sugo e servi.",
    ],
  },
  {
    id: "ceci_tonno",
    nome: "Insalata di ceci e tonno",
    emoji: "🥗", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    tipi: ["veloce", "proteico", "sano"],
    diete: ["pescetariano", "senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: ["pesce"],
    nutrizione: { kcal: 390, proteine: 28, carboidrati: 36, grassi: 14 },
    ingredienti: [
      { nome: "Ceci lessati",        categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.50 },
      { nome: "Tonno in scatola",    categoria: "Scatolame e conserve",   quantita: "160 g",  prezzo: 1.40 },
      { nome: "Cipolla rossa",       categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Scola ceci e tonno.",
      "Unisci con cipolla affettata e pomodorini.",
      "Condisci con olio, sale e pepe e servi.",
    ],
  },
  {
    id: "vellutata_zucca",
    nome: "Vellutata di zucca",
    emoji: "🎃", tempo: 30, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["autunno", "inverno"],
    tipi: ["sano", "economico"],
    diete: ["vegetariano", "vegano", "senza_glutine", "senza_lattosio"],
    allergeni: [],
    nutrizione: { kcal: 240, proteine: 6, carboidrati: 34, grassi: 8 },
    ingredienti: [
      { nome: "Zucca",               categoria: "Frutta e verdura",       quantita: "500 g",  prezzo: 1.20 },
      { nome: "Patata",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Cipolla",             categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Brodo vegetale",      categoria: "Scatolame e conserve",   quantita: "500 ml", prezzo: 0.20 },
    ],
    passi: [
      "Soffriggi la cipolla, aggiungi zucca e patata a cubetti.",
      "Copri con il brodo e cuoci 25 minuti.",
      "Frulla fino a ottenere una crema liscia e servi.",
    ],
  },
  {
    id: "tacchino_riso_broccoli",
    nome: "Tacchino con riso basmati e broccoli",
    emoji: "🍛", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["proteico", "sano"],
    diete: ["senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: [],
    nutrizione: { kcal: 460, proteine: 40, carboidrati: 48, grassi: 10 },
    ingredienti: [
      { nome: "Fesa di tacchino",    categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 2.50 },
      { nome: "Riso basmati",        categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 0.70 },
      { nome: "Broccoli",            categoria: "Frutta e verdura",       quantita: "300 g",  prezzo: 1.40 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa il riso e cuoci i broccoli a vapore.",
      "Rosola il tacchino a dadini in padella con olio.",
      "Unisci tutto, regola di sale e servi.",
    ],
  },
  {
    id: "caprese_pane",
    nome: "Caprese con pane",
    emoji: "🍅", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    riscaldabile: false, stagioni: ["primavera", "estate"],
    tipi: ["veloce", "sfizioso"],
    diete: ["vegetariano"],
    allergeni: ["lattosio", "glutine"],
    nutrizione: { kcal: 420, proteine: 20, carboidrati: 30, grassi: 24 },
    ingredienti: [
      { nome: "Mozzarella",          categoria: "Latticini e uova",       quantita: "250 g",  prezzo: 2.20 },
      { nome: "Pomodori",            categoria: "Frutta e verdura",       quantita: "3",      prezzo: 0.90 },
      { nome: "Pane",                categoria: "Pane e panetteria",      quantita: "200 g",  prezzo: 0.60 },
      { nome: "Basilico",            categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.30 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Affetta pomodori e mozzarella e disponili a strati.",
      "Condisci con olio, sale e basilico.",
      "Servi con il pane.",
    ],
  },
  {
    id: "aglio_olio_peperoncino",
    nome: "Spaghetti aglio, olio e peperoncino",
    emoji: "🌶️", tempo: 15, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    piccante: true,
    tipi: ["veloce", "economico", "classico"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 480, proteine: 12, carboidrati: 80, grassi: 12 },
    ingredienti: [
      { nome: "Spaghetti",           categoria: "Pasta, riso e cereali",  quantita: "200 g",  prezzo: 0.40 },
      { nome: "Aglio",               categoria: "Frutta e verdura",       quantita: "2 spicchi", prezzo: 0.15 },
      { nome: "Peperoncino",         categoria: "Condimenti e spezie",    quantita: "1",      prezzo: 0.10 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "3 cucchiai", prezzo: 0.45 },
      { nome: "Prezzemolo",          categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.20 },
    ],
    passi: [
      "Lessa gli spaghetti al dente.",
      "Rosola aglio e peperoncino nell'olio senza bruciarli.",
      "Salta la pasta nel condimento, aggiungi prezzemolo e servi.",
    ],
  },
  {
    id: "quinoa_bowl",
    nome: "Bowl di quinoa con verdure e avocado",
    emoji: "🥗", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["primavera", "estate"],
    tipi: ["sano", "sfizioso"],
    diete: ["vegetariano", "vegano", "senza_glutine", "senza_lattosio"],
    allergeni: [],
    nutrizione: { kcal: 440, proteine: 14, carboidrati: 54, grassi: 18 },
    ingredienti: [
      { nome: "Quinoa",              categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 1.30 },
      { nome: "Avocado",             categoria: "Frutta e verdura",       quantita: "1",      prezzo: 1.00 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Mais",                categoria: "Scatolame e conserve",   quantita: "150 g",  prezzo: 0.60 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa la quinoa e falla raffreddare.",
      "Taglia avocado e pomodorini, scola il mais.",
      "Componi la bowl, condisci con olio e limone e servi.",
    ],
  },
  {
    id: "tofu_saltato",
    nome: "Tofu saltato con verdure e riso",
    emoji: "🍱", tempo: 20, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    tipi: ["sano", "proteico"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["soia"],
    nutrizione: { kcal: 420, proteine: 22, carboidrati: 52, grassi: 12 },
    ingredienti: [
      { nome: "Tofu",                categoria: "Frutta e verdura",       quantita: "250 g",  prezzo: 1.30 },
      { nome: "Riso",                categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 0.40 },
      { nome: "Verdure miste",       categoria: "Surgelati",              quantita: "300 g",  prezzo: 1.20 },
      { nome: "Salsa di soia",       categoria: "Condimenti e spezie",    quantita: "3 cucchiai", prezzo: 0.40 },
    ],
    passi: [
      "Lessa il riso. Salta il tofu a cubetti in padella finché dorato.",
      "Aggiungi le verdure e la salsa di soia, salta a fiamma alta.",
      "Servi sul riso.",
    ],
  },
  {
    id: "orata_cartoccio",
    nome: "Orata al cartoccio con zucchine",
    emoji: "🐟", tempo: 25, slot: ["pranzo", "cena"], attrezzatura: ["forno"],
    tipi: ["sano", "sfizioso", "proteico"],
    diete: ["pescetariano", "senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: ["pesce"],
    nutrizione: { kcal: 360, proteine: 36, carboidrati: 12, grassi: 18 },
    ingredienti: [
      { nome: "Orata (filetti)",     categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 4.00 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.85 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.25 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Disponi i filetti su carta forno con zucchine a rondelle.",
      "Condisci con olio, limone, sale e chiudi il cartoccio.",
      "Cuoci in forno a 190° per 20 minuti e servi.",
    ],
  },

  /* ---------- ESTIVE FRESCHE (poca o nessuna cottura) ---------- */
  {
    id: "insalata_greca_ceci",
    nome: "Insalata greca con ceci e feta",
    emoji: "🥗", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["sano", "veloce"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 380, proteine: 18, carboidrati: 30, grassi: 20 },
    ingredienti: [
      { nome: "Ceci lessati",        categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.55 },
      { nome: "Feta",                categoria: "Latticini e uova",       quantita: "100 g",  prezzo: 1.00 },
      { nome: "Peperone",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.55 },
      { nome: "Pomodori",            categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.50 },
      { nome: "Cipolla rossa",       categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
      { nome: "Olive nere",          categoria: "Scatolame e conserve",   quantita: "50 g",   prezzo: 0.60 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
      { nome: "Origano",             categoria: "Condimenti e spezie",    quantita: "1 pizzico", prezzo: 0.05 },
    ],
    passi: [
      "Scola i ceci e taglia peperone, pomodori e cipolla a cubetti.",
      "Unisci in una ciotola con la feta a dadini e le olive.",
      "Condisci con olio e origano e servi fresca (niente cottura).",
    ],
  },
  {
    id: "bowl_tonno_fagioli",
    nome: "Bowl di tonno, fagioli e mais",
    emoji: "🥗", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["proteico", "veloce", "economico"],
    diete: ["pescetariano", "senza_glutine", "senza_lattosio", "iperproteico"],
    allergeni: ["pesce"],
    nutrizione: { kcal: 400, proteine: 32, carboidrati: 30, grassi: 14 },
    ingredienti: [
      { nome: "Tonno al naturale",   categoria: "Scatolame e conserve",   quantita: "160 g",  prezzo: 1.80 },
      { nome: "Fagioli cannellini",  categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.55 },
      { nome: "Mais",                categoria: "Scatolame e conserve",   quantita: "150 g",  prezzo: 0.60 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 0.90 },
      { nome: "Cipolla rossa",       categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Scola tonno, fagioli e mais.",
      "Unisci in una ciotola con i pomodorini e la cipolla a fettine.",
      "Condisci con olio (e un po' di limone) e servi.",
    ],
  },
  {
    id: "tofu_bowl_verdure",
    nome: "Bowl di tofu marinato con carote e peperoni",
    emoji: "🥢", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["proteico", "sano"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["soia", "glutine"],
    nutrizione: { kcal: 320, proteine: 18, carboidrati: 18, grassi: 16 },
    ingredienti: [
      { nome: "Tofu",                categoria: "Frutta e verdura",       quantita: "350 g",  prezzo: 1.80 },
      { nome: "Carote",              categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.30 },
      { nome: "Peperoni",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.65 },
      { nome: "Salsa di soia",       categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
      { nome: "Semi di sesamo",      categoria: "Condimenti e spezie",    quantita: "10 g",   prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.15 },
    ],
    passi: [
      "Taglia il tofu a cubetti e marinalo qualche minuto con la salsa di soia.",
      "Taglia carote e peperoni a listarelle sottili.",
      "Unisci tutto, spolvera di sesamo e un filo d'olio. Nessuna cottura.",
    ],
  },
  {
    id: "piadina_fredda_tacchino",
    nome: "Piadina fredda con tacchino e mozzarella",
    emoji: "🌯", tempo: 8, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["proteico", "veloce"],
    diete: [],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 450, proteine: 30, carboidrati: 38, grassi: 18 },
    ingredienti: [
      { nome: "Piadine",             categoria: "Pane e panetteria",      quantita: "2",      prezzo: 0.70 },
      { nome: "Fesa di tacchino",    categoria: "Carne e pesce",          quantita: "120 g",  prezzo: 1.60 },
      { nome: "Mozzarella",          categoria: "Latticini e uova",       quantita: "125 g",  prezzo: 0.85 },
      { nome: "Insalata",            categoria: "Frutta e verdura",       quantita: "60 g",   prezzo: 0.40 },
      { nome: "Pomodoro",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.25 },
    ],
    passi: [
      "Farcisci le piadine (fredde) con tacchino, mozzarella a fette, insalata e pomodoro.",
      "Arrotola e taglia a metà.",
      "Pronta da portare: niente da cuocere o riscaldare.",
    ],
  },
  {
    id: "insalata_lenticchie_feta",
    nome: "Insalata di lenticchie, feta e menta",
    emoji: "🥗", tempo: 10, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["sano", "proteico", "veloce"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 390, proteine: 20, carboidrati: 34, grassi: 16 },
    ingredienti: [
      { nome: "Lenticchie lessate",  categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.60 },
      { nome: "Feta",                categoria: "Latticini e uova",       quantita: "100 g",  prezzo: 1.00 },
      { nome: "Peperone",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.55 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Cipolla rossa",       categoria: "Frutta e verdura",       quantita: "1/2",    prezzo: 0.15 },
      { nome: "Menta",               categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.10 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Scola le lenticchie e taglia peperone, pomodorini e cipolla.",
      "Unisci con la feta a dadini e la menta spezzettata.",
      "Condisci con olio e succo di limone. Fredda e pronta.",
    ],
  },
  {
    id: "couscous_freddo_ceci",
    nome: "Cous cous freddo con ceci e verdure",
    emoji: "🥗", tempo: 12, slot: ["pranzo", "cena"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["sano", "economico", "veloce"],
    diete: ["vegetariano", "vegano", "senza_lattosio"],
    allergeni: ["glutine"],
    nutrizione: { kcal: 410, proteine: 15, carboidrati: 60, grassi: 12 },
    ingredienti: [
      { nome: "Cous cous",           categoria: "Pasta, riso e cereali",  quantita: "160 g",  prezzo: 0.65 },
      { nome: "Ceci lessati",        categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.55 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 0.90 },
      { nome: "Zucchine",            categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.45 },
      { nome: "Menta",               categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.10 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Idrata il cous cous con acqua bollente, coprilo e sgranalo con la forchetta; lascialo raffreddare.",
      "Unisci ceci, pomodorini e zucchina grattugiata a crudo.",
      "Condisci con olio, limone e menta. Si mangia fredda.",
    ],
  },
  {
    id: "pasta_fredda_mozzarella",
    nome: "Pasta fredda integrale con mozzarella e pomodorini",
    emoji: "🍝", tempo: 15, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["estate"],
    tipi: ["classico", "veloce"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 460, proteine: 20, carboidrati: 60, grassi: 15 },
    ingredienti: [
      { nome: "Pasta integrale",     categoria: "Pasta, riso e cereali",  quantita: "180 g",  prezzo: 0.55 },
      { nome: "Mozzarella",          categoria: "Latticini e uova",       quantita: "125 g",  prezzo: 0.85 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "200 g",  prezzo: 0.90 },
      { nome: "Olive nere",          categoria: "Scatolame e conserve",   quantita: "40 g",   prezzo: 0.50 },
      { nome: "Basilico",            categoria: "Frutta e verdura",       quantita: "qualche foglia", prezzo: 0.10 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Lessa la pasta al dente e raffreddala sotto acqua fredda (cuocila anche in anticipo, la mattina presto).",
      "Unisci mozzarella a cubetti, pomodorini e olive.",
      "Condisci con olio e basilico e tieni in frigo fino a servire.",
    ],
  },
  {
    id: "insalata_pollo_yogurt",
    nome: "Insalata di pollo con salsa allo yogurt",
    emoji: "🥗", tempo: 15, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["estate"],
    tipi: ["proteico", "sano"],
    diete: ["senza_glutine", "iperproteico"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 400, proteine: 38, carboidrati: 18, grassi: 18 },
    ingredienti: [
      { nome: "Petto di pollo",      categoria: "Carne e pesce",          quantita: "300 g",  prezzo: 2.10 },
      { nome: "Yogurt greco",        categoria: "Latticini e uova",       quantita: "150 g",  prezzo: 0.80 },
      { nome: "Insalata mista",      categoria: "Frutta e verdura",       quantita: "100 g",  prezzo: 0.70 },
      { nome: "Pomodorini",          categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.70 },
      { nome: "Carota",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.15 },
    ],
    passi: [
      "Cuoci il petto di pollo (meglio in anticipo, per non accendere i fornelli col caldo) e taglialo a striscioline.",
      "Prepara una salsa con yogurt, limone, olio e sale.",
      "Unisci pollo, insalata, pomodorini e carota grattugiata e condisci con la salsa. Si serve fredda.",
    ],
  },
  {
    id: "hummus_bowl_uova",
    nome: "Bowl di hummus, uova sode e verdure",
    emoji: "🥙", tempo: 12, slot: ["pranzo", "cena"], attrezzatura: ["fornelli"],
    stagioni: ["estate"],
    tipi: ["sano", "proteico"],
    diete: ["vegetariano", "senza_glutine", "senza_lattosio"],
    allergeni: ["uova"],
    nutrizione: { kcal: 380, proteine: 20, carboidrati: 26, grassi: 22 },
    ingredienti: [
      { nome: "Ceci lessati",        categoria: "Scatolame e conserve",   quantita: "240 g",  prezzo: 0.55 },
      { nome: "Tahin (crema di sesamo)", categoria: "Condimenti e spezie", quantita: "20 g",  prezzo: 0.40 },
      { nome: "Uova",                categoria: "Latticini e uova",       quantita: "4",      prezzo: 1.12 },
      { nome: "Carote",              categoria: "Frutta e verdura",       quantita: "2",      prezzo: 0.30 },
      { nome: "Sedano",              categoria: "Frutta e verdura",       quantita: "2 coste", prezzo: 0.30 },
      { nome: "Limone",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Olio EVO",            categoria: "Condimenti e spezie",    quantita: "2 cucchiai", prezzo: 0.30 },
    ],
    passi: [
      "Frulla ceci, tahin, olio, limone e un po' d'acqua fino a ottenere l'hummus.",
      "Rassoda le uova (anche in anticipo) e tagliale a metà.",
      "Servi l'hummus con le uova e le verdure a bastoncino.",
    ],
  },
  {
    id: "overnight_oats",
    nome: "Overnight oats con yogurt e frutta",
    emoji: "🥣", tempo: 5, slot: ["colazione"], attrezzatura: [],
    tipi: ["sano", "proteico", "veloce"],
    diete: ["vegetariano"],
    allergeni: ["glutine", "lattosio"],
    nutrizione: { kcal: 380, proteine: 22, carboidrati: 48, grassi: 10 },
    ingredienti: [
      { nome: "Fiocchi d'avena",     categoria: "Pasta, riso e cereali",  quantita: "100 g",  prezzo: 0.40 },
      { nome: "Yogurt greco",        categoria: "Latticini e uova",       quantita: "250 g",  prezzo: 1.35 },
      { nome: "Latte",               categoria: "Latticini e uova",       quantita: "100 ml", prezzo: 0.10 },
      { nome: "Frutta fresca",       categoria: "Frutta e verdura",       quantita: "150 g",  prezzo: 0.90 },
      { nome: "Semi di chia",        categoria: "Condimenti e spezie",    quantita: "15 g",   prezzo: 0.25 },
      { nome: "Miele",               categoria: "Condimenti e spezie",    quantita: "1 cucchiaio", prezzo: 0.20 },
    ],
    passi: [
      "La sera mescola avena, yogurt, latte e chia in un barattolo.",
      "Lascia in frigo tutta la notte.",
      "Al mattino aggiungi frutta fresca e un filo di miele. Nessuna cottura.",
    ],
  },
  {
    id: "frullato_proteico_estivo",
    nome: "Frullato proteico con frutta estiva",
    emoji: "🥤", tempo: 5, slot: ["colazione"], attrezzatura: [],
    stagioni: ["estate"],
    tipi: ["proteico", "veloce", "sano"],
    diete: ["vegetariano", "senza_glutine"],
    allergeni: ["lattosio"],
    nutrizione: { kcal: 320, proteine: 26, carboidrati: 38, grassi: 6 },
    ingredienti: [
      { nome: "Yogurt greco (o Skyr)", categoria: "Latticini e uova",     quantita: "250 g",  prezzo: 1.35 },
      { nome: "Banana",              categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.20 },
      { nome: "Pesca",               categoria: "Frutta e verdura",       quantita: "1",      prezzo: 0.40 },
      { nome: "Frutti di bosco",     categoria: "Frutta e verdura",       quantita: "100 g",  prezzo: 1.50 },
      { nome: "Latte",               categoria: "Latticini e uova",       quantita: "150 ml", prezzo: 0.15 },
    ],
    passi: [
      "Metti tutto nel frullatore.",
      "Frulla fino a ottenere un frullato cremoso.",
      "Versa e bevi subito, ben fresco.",
    ],
  },
];
